### ISSUE TITLE
Auto build & publish the pages after the PR merged

### ISSUE THREAD

**Issue by imbajin** [apache/incubator-hugegraph-doc#147]
Github publish its official page action like [hugo](https://github.com/apache/incubator-hugegraph-doc/actions/new?category=pages)

maybe it could meet the basic need as the title says, we could try it to find the suitable way

**Comment by imbajin** [comment]
Github publish its official page action like [hugo](https://github.com/apache/incubator-hugegraph-doc/actions/new?category=pages)

maybe it could meet the basic need as the title says, we could try it to find the suitable way

**Comment by imbajin** [comment]
@damonxue would u like to have a try? 😄

**Comment by damonxue** [comment]
Ok， pls assign to me. u mean use [hugo](https://github.com/gohugoio/hugo), is that true? Or maybe we can use [actions-gh-pages](https://github.com/peaceiris/actions-gh-pages). I active in Apache Shenyu, It's web site use gh-pages. so pls tell me why, thanks.

**Comment by imbajin** [comment]
> Ok， pls assign to me. u mean use [hugo](https://github.com/gohugoio/hugo), is that true? Or maybe we can use [actions-gh-pages](https://github.com/peaceiris/actions-gh-pages). I active in Apache Shenyu, It's web site use gh-pages. so pls tell me why, thanks.

Nope, I'm not sure it's the best choice, just found it recently (seems the action u mentioned is not published by the Official Github), how could it run in apache's repo? (or it's a special case?)

U can use any action(could run with the `apache action's rules`) to achieve the goal.(Of course, the official plan can be considered priority)
