### ISSUE TITLE
[Question] hugegraph-client 文档依赖过时 - 需更新

### ISSUE THREAD

**Issue by zhenyuT** [apache/incubator-hugegraph-doc#217]
### Problem Type (问题类型)

struct / logic (架构 / 逻辑问题)

### Your Question (问题描述)

https://hugegraph.apache.org/cn/docs/quickstart/hugegraph-client/

4.2节
```
<dependencies>
    <dependency>
        <groupId>com.baidu.hugegraph</groupId>
        <artifactId>hugegraph-client</artifactId>
        <version>${version}</version>
    </dependency>    
</dependencies>
```
这里的依赖和下面代码的包名都还是百度的，应该用apache的比较好吧？

**Comment by imbajin** [comment]
是的, 这是因为之前旧文档遗留的没有更新到位.

可以的话可以帮忙 fix 一下, 另外全文搜索一下 "com.baidu" 关键字, 替换为 "org.apache", THX

**Comment by zhenyuT** [comment]
好的，晚点我提个PR
