### ISSUE TITLE
[Question] 请问repeat和in是不能组合使用吗？

### ISSUE THREAD

**Issue by zhenyuT** [apache/incubator-hugegraph-doc#231]
### Problem Type (问题类型)

others (please edit later)

### Your Question (问题描述)

使用example里面的schema和数据
使用g.V("josh").repeat(out()).times(1)能正常执行
使用g.V("josh").repeat(in()).times(1)就报错
但是我的意图就是想反向循环遍历

![image](https://github.com/apache/incubator-hugegraph-doc/assets/9477681/611ffe0b-5c91-4617-a1d4-5b8125b39108)

**Comment by imbajin** [comment]
可能是你这样嵌套的写法有误吧，看看语法嵌套规则

**Comment by zhenyuT** [comment]
> 

为什么out就可以，in就不行呢？

**Comment by zhenyuT** [comment]
repeat(inE().outV())可以正常执行，结果也是符合我预期的

但是为什么repeat(in())就不行呢？

**Comment by zhenyuT** [comment]
问题解决了把repeat(in)改成repeat(__.in())就行了

参考：https://issues.apache.org/jira/browse/TINKERPOP-727
