### ISSUE TITLE
[Doc] Add mail subscribe way in "Community" page & README

### ISSUE THREAD

**Issue by imbajin** [apache/incubator-hugegraph-doc#257]
## WANTED FOR EVERYONE to take this task 📫 

Also add https://lists.apache.org/list.html?dev@hugegraph.apache.org for users to read all the mail easily

![Image](https://user-images.githubusercontent.com/17706099/242567494-f677f892-d706-4ca9-a682-a7323e86197c.png)

- https://hugegraph.apache.org/community/ (community page, and the Chinese page need translate)
- https://hugegraph.apache.org/docs/contribution-guidelines/subscribe/ (how to subscribe mailing list)
- https://github.com/apache/incubator-hugegraph/issues/1749 (cn issue)

Update `README` to add these info:
- how to subscribe dev mail, and try to send it after 24h later if u don't receive the reply mail (in english)
- mailing list [url](https://lists.apache.org/list.html?dev@hugegraph.apache.org) for all to visit directly
- don't send mail to `dev` until u subscribe the mailing list successfully (otherwise the mail will be banned)

U could **comment** in this issue to address the improvement & submit a `PR` to **link** with it

**Comment by msgui** [comment]
Hi, @imbajin, I want to try. Please assign to me
