### ISSUE TITLE
[Question] download link should be updated in the doc

### ISSUE THREAD

**Issue by aroundabout** [apache/incubator-hugegraph-doc#277]
### Problem Type (问题类型)

typo (错别字和描述优化)

### Your Question (问题描述)

doc link: https://hugegraph.apache.org/docs/quickstart/hugegraph-computer/#21-download-the-compiled-archive

the lastest download link from the release of computer repo is https://downloads.apache.org/incubator/hugegraph/1.0.0/apache-hugegraph-computer-incubating-1.0.0.tar.gz

this link should be updated

![snapshot of hugegraph doc](https://github.com/apache/incubator-hugegraph-doc/assets/49650772/6e69e7b4-9b7f-48cb-90b5-bd808052f942)

**Comment by imbajin** [comment]
yep，could u submit a PR to fix it？（also could check other outdated doc in computer page）

**Comment by aroundabout** [comment]
Ok, I will fix it later
