### ISSUE TITLE
Swagger requires login but does not have this option

### ISSUE THREAD

**Issue by Zhang88665** [apache/incubator-hugegraph-doc#304]
### Problem Type (问题类型)

None

### Your Question (问题描述)

I have configured user authentication for hugegraph, but the Swagger interface cannot be opened, prompting 401. Where should I enter my username and password?

![image](https://github.com/apache/incubator-hugegraph-doc/assets/87627782/3f50cf85-3356-40e1-9361-5d0bc08d921d)

**Comment by imbajin** [comment]
Which server version do u use? Auth was supported in latest master code (not 1.0.0, ready in docker latest images or 1.2.0)

@SunnyBoy-WYH Could take a look on it later?

**Comment by Zhang88665** [comment]
Version 1.0.0, deployed locally using the tar package

**Comment by imbajin** [comment]
> Version 1.0.0, deployed locally using the tar package

refer https://github.com/apache/incubator-hugegraph/pull/2360

**Comment by imbajin** [comment]
@Zhang88665 already supported in `1.2.0` (u could try docker image to use it)

<img width="1417" alt="image" src="https://github.com/apache/incubator-hugegraph-doc/assets/17706099/f951c098-7fe3-4dc7-8232-9d200c54d522">

2 ways:
<img width="1232" alt="image" src="https://github.com/apache/incubator-hugegraph-doc/assets/17706099/4f37ecdd-bda2-44ea-b14f-fd9fa91037cb">
