### ISSUE TITLE
[BUG] Website MUST have Incubation disclaimer on all pages

### ISSUE THREAD

**Issue by sebbASF** [apache/incubator-hugegraph-doc#359]
### Problem Type (问题类型)

lack info (文档描述缺失)

### Your Question (问题描述)

Website MUST have Incubation disclaimer on all pages.
The disclaimer is currently only on the home page as far as I can tell.
That is not sufficient, all public facing documentation should include the disclaimer

**Comment by imbajin** [comment]
> ### Problem Type (问题类型)
> 
> lack info (文档描述缺失)
> 
> ### Your Question (问题描述)
> 
> Website MUST have Incubation disclaimer on all pages.
> The disclaimer is currently only on the home page as far as I can tell.
> That is not sufficient, all public facing documentation should include the disclaimer

thanks for the reminder, we'll add it soon

**Comment by liuxiaocs7** [comment]
Hi, @sebbASF, we have add Incubation disclaimer on all pages by #360, plz take a look.
